################################################
#               Survival Games                 #
#                                              #
#                Developed by                  #
#    Beechboy200, Double0negative, Chaseos     #
#                                              #
#             Version: alpha 0.0.1             #
#                                              #
#              Skitscape.net                   #
################################################


#set how many players are needed for the game
#to auto-start. Once the player limit is reached
#it will wait for x amount of seconds for 
#additional players
auto-start-limit: 24
auto-start-time: 60

#set the max number of Simultaneous Games
max-games: 2

#if set to true, commands not associated with
#the survival games will not be allowed to 
#players in-game
disallow-commands: true

#set how long each player should
#be invincible for after the start of 
#the game in seconds
damage-time-limit: 60

#if mob-progression is enabled, then the 
#difficulty of mobs and amount of mobs
#spawning will increase with a decrease 
#of players. The ratio defines how much 
#harder it should get for every person 
#out. a ratio of 2 whould mean 2x harder
#The mob blacklist definesmobs that should 
#not spawn. 
mob-progression:
  enabled: true
  ratio: 2
  mob-blacklist:
  - slime
#if set to true, the arena will be logged
#and auto rolled back and the end of the 
#game
logging:
  enabled: true
  
#settings for the endgame. This enables
#when there are only x amount of players
#remaining. If place chest is enabled then
#when the player limit is reached, a chest
#will be placed inside the radius of every 
#remain player contianing random items for 
<<<<<<< HEAD
#that player. If fire-lighting is enabled
#the a lighting strike will be fired at the
#location of each player every x seconds to
#notify the other players of their location
=======
#that player
>>>>>>> 0fbcc28d77fcfe110e112c66900a2f5e1ebcd5f9
endgame:
  players: 3
  place-chest:
    enabled: true
    radius: 10
  fire-lighting:
    enabled: true
    time: 20

#settings for connecting to the 
#sql server. These settings will
#be used for both the online webstats
#and for logging block changes for the 
#automated rollback
sql:
  host: 'localhost'
  port: 3306
  user: 'root'
  pass: ''
  database:

#Settings for the webstats. If enabled, stats 
#such as k/d record, wins, win streaks, kill
#streaks etc will be saved. If verbose mode is
#enabled then it will keep stats on every single game
#instead of just for each player. If webserver is 
#enabled then a webserver will be started on the
#<yourserverip>:<port> and allow people to view
#the stats online.
stats:
  enabled: true
  verbose: true
  webserver:
    enabled: true
    port: 880